### ISSUE TITLE
Compatibility with Slonik v33+?

### ISSUE THREAD

**Issue by aust1nz** [gajus/eslint-plugin-sql#21]
When I run this plugin on Slonik v33+, I'm getting:
```
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
```

I _think_ this is because `sql.unsafe` is unexpected, but I'm not really sure how to read eslint plugins. Unfortunately, not sure of a fix here, but thought I'd flag as a potential compatibility bug.

**Comment by aust1nz** [comment]
Cheers, thanks!

**Comment by andymakingthings** [comment]
I'm still getting this error with version 2.3.2. Error trace:

```
Rule: "sql/no-unsafe-query"
    at TemplateLiteral (node_modules/eslint-plugin-sql/dist/src/rules/noUnsafeQuery.js:34:86)
    at ruleErrorHandler (node_modules/eslint/lib/linter/linter.js:1115:28)
    at node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at node_modules/eslint/lib/linter/linter.js:1150:32
```

The line in question (`noUnsafeQuery.js:34:86`):

```js
const legacyTagName = tag === null || tag === void 0 ? void 0 : tag.name.toLowerCase();
```

Changing it to this prevented the error, although I'm not sure if it's correct:

```js
const legacyTagName = tag === null || tag === void 0 || tag.name === void 0 ? void 0 : tag.name.toLowerCase();
```

I think this would be accomplished by changing [`noUnsafeQuery.ts:45`](https://github.com/gajus/eslint-plugin-sql/blob/d968b18db5a8a479c2f462d5fd4d59e1f9427211/src/rules/noUnsafeQuery.ts#L45) from:

```ts
      const legacyTagName = tag?.name.toLowerCase();
```

to:

```ts
      const legacyTagName = tag?.name?.toLowerCase();
```

I don't know if this is correct, though, because I'm not sure if `tag`, when defined, should always definitely have `name`.
